services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rails
    environment:
          MYSQL_HOST: db
          MYSQL_USER: dev
          MYSQL_PASSWORD: secret
          MYSQL_DB: development
          RAILS_ENV: development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle 
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - dev_network

  db:
    image: mysql:8.4
    platform: linux/arm64/v8
    container_name: mysql
    volumes:
      - rails_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: development
      TZ: 'Asia/Tokyo'
    networks:
      - dev_network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailhog-data:/data

volumes:
  bundle:
  rails_mysql_data:
  mailhog-data:

networks:
  dev_network:
    name: dev_network
